/** The installable, offline game (docs/07 §13.7) as a Vite plugin:
 *
 *   - the icons, drawn at build time (scripts/icons.mjs), and the web app
 *     manifest, emitted into the build — nothing binary in the repo;
 *   - their <link> tags, injected into index.html (dev too, where a small
 *     middleware serves the same files so the page never 404s);
 *   - sw.js, written after the bundle: it precaches every built file under a
 *     cache named for the build's content hash, serves them offline, and
 *     drops older caches when it activates. Production only: the dev server
 *     (and every test on it) never registers a worker (src/pwa.ts).
 *
 *  Every URL is relative: the site is served from a subpath (GitHub Pages). */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ICONS, moonPng } from './icons.mjs';

export const THEME = '#0e0f11';

export const MANIFEST = {
  name: 'MOONSHOTS · Base Builder',
  short_name: 'Moonshots',
  description: 'From regolith to Dyson swarm — build a base on the Moon.',
  start_url: './',
  scope: './',
  display: 'fullscreen',
  display_override: ['fullscreen', 'standalone'],
  orientation: 'landscape',
  background_color: THEME,
  theme_color: THEME,
  categories: ['games'],
  icons: [
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};

/** the service worker, for a cache name and the files it precaches */
export function serviceWorker(cache, files) {
  return `/* MOONSHOTS service worker — generated by scripts/pwa.mjs at build time. */
const CACHE = ${JSON.stringify(cache)};
const PRECACHE = ${JSON.stringify(files, null, 1)};
const SHELL = new URL('./index.html', self.location).href;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
});

// the page's "Update ready" chip asks the waiting version to take over
self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('mbb-') && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

// cache first: the built files never change under one name; a page load
// (any query string: ?debug, ?site=…) is the cached shell
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match(SHELL).then((r) => r || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req).then((r) => r || fetch(req)));
});
`;
}

/** @returns {import('vite').Plugin} */
export function pwa() {
  let outDir = 'dist';
  const files = () => [
    ...ICONS.map((ic) => ({ fileName: ic.file, source: () => moonPng(ic.size), type: 'image/png' })),
    { fileName: 'manifest.webmanifest', source: () => JSON.stringify(MANIFEST, null, 2), type: 'application/manifest+json' },
  ];
  return {
    name: 'moonshots-pwa',
    configResolved(config) {
      outDir = join(config.root, config.build.outDir);
    },
    transformIndexHtml() {
      return [
        { tag: 'link', attrs: { rel: 'manifest', href: './manifest.webmanifest' }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: './icons/apple-touch-icon.png' }, injectTo: 'head' },
      ];
    },
    // dev: the same manifest and icons, drawn on request
    configureServer(server) {
      const byPath = new Map(files().map((f) => [`/${f.fileName}`, f]));
      server.middlewares.use((req, res, next) => {
        const f = byPath.get((req.url ?? '').split('?')[0]);
        if (!f) { next(); return; }
        res.setHeader('Content-Type', f.type);
        res.end(f.source());
      });
    },
    generateBundle() {
      for (const f of files()) this.emitFile({ type: 'asset', fileName: f.fileName, source: f.source() });
    },
    // after every file is written: the worker names the cache for all of them
    writeBundle(_options, bundle) {
      const names = Object.keys(bundle).filter((n) => !n.endsWith('.map') && n !== 'sw.js').sort();
      const h = createHash('sha256');
      for (const n of names) {
        const item = bundle[n];
        h.update(n);
        h.update(item.type === 'chunk' ? item.code : item.source);
      }
      const cache = `mbb-${h.digest('hex').slice(0, 12)}`;
      writeFileSync(join(outDir, 'sw.js'), serviceWorker(cache, ['./', ...names.map((n) => `./${n}`)]));
    },
  };
}
